# Generated by Django 5.0.2 on 2024-06-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0002_alter_artikel_options_alter_kategori_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artikel',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
    ]
